/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ACheckboxGroup: typeof import('ant-design-vue/es')['CheckboxGroup']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuDivider: typeof import('ant-design-vue/es')['MenuDivider']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AResult: typeof import('ant-design-vue/es')['Result']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    CastTransform: typeof import('./../components/pipeline/transforms/CastTransform.vue')['default']
    ContextMenu: typeof import('./../components/common/ContextMenu.vue')['default']
    DataPreviewPanel: typeof import('./../components/pipeline/DataPreviewPanel.vue')['default']
    DataTable: typeof import('./../components/pipeline/DataTable.vue')['default']
    FilterTransform: typeof import('./../components/pipeline/transforms/FilterTransform.vue')['default']
    GenericTransform: typeof import('./../components/pipeline/transforms/GenericTransform.vue')['default']
    GraphCanvas: typeof import('./../components/pipeline/GraphCanvas.vue')['default']
    GroupByTransform: typeof import('./../components/pipeline/transforms/GroupByTransform.vue')['default']
    JoinTransform: typeof import('./../components/pipeline/transforms/JoinTransform.vue')['default']
    NodeToolbar: typeof import('./../components/pipeline/NodeToolbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SortTransform: typeof import('./../components/pipeline/transforms/SortTransform.vue')['default']
    ToolButton: typeof import('./../components/common/ToolButton.vue')['default']
    TransformConfigPanel: typeof import('./../components/pipeline/TransformConfigPanel.vue')['default']
    TransformPanel: typeof import('./../components/pipeline/TransformPanel.vue')['default']
  }
}
